---
version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ./config/homeassistant/blueprints/:/config/blueprints/
      - ./config/homeassistant/configuration/:/config/configuration/
      - ./config/homeassistant/custom_components/:/config/custom_components/
      - ./config/homeassistant/themes/:/config/themes/
      - ./config/homeassistant/www/:/config/www/

      - ./config/homeassistant/automations.yaml:/config/automations.yaml
      - ./config/homeassistant/configuration.yaml:/config/configuration.yaml
      - ./config/homeassistant/scenes.yaml:/config/scenes.yaml
      - ./config/homeassistant/scripts.yaml:/config/scripts.yaml
      - ./config/homeassistant/secrets.yaml:/config/secrets.yaml

      - ./data/homeassistant:/config

      # - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ETC/UTC
    ports:
      - 8123:8123
    depends_on:
      - mariadb
      - mosquitto
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/mariadb:/config
      - ./log/mariadb:/config/log
    ports:
      - "3306:3306"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    ports:
      - "1883:1883"
    volumes:
      - "./config/mosquitto:/mosquitto/config"
      - "./data/mosquitto:/mosquitto/data"
      - "./log/mosquitto:/mosquitto/log"
    environment:
      - TZ=ETC/UTC
    restart: unless-stopped

  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui
    devices:
      - ${ZWAVE_DEVICE_ID}:/dev/zwave
    env_file:
      - .env
    environment:
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/db
    ports:
      - 3002:3000
      - 8091:8091
    volumes:
      - ./data/zwave-js-ui/store:/usr/src/app/store
      - ./data/zwave-js-ui/db:/usr/src/app/db
    restart: unless-stopped
