---
version: '3'

services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant
    volumes:
      - ./data/homeassistant:/config

      # - /sys/class/thermal/thermal_zone0/temp:/sys/class/thermal/thermal_zone0/temp
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ETC/UTC
    ports:
      - 8123:8123
    depends_on:
      - mariadb
      - mosquitto
    restart: unless-stopped

  mariadb:
    image: linuxserver/mariadb
    container_name: mariadb
    env_file: .env
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./data/mariadb:/config
      - ./log/mariadb:/config/log
    ports:
      - "3306:3306"
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    user: "1000:1000"
    ports:
      - "1883:1883"
    volumes:
      - "./config/mosquitto:/mosquitto/config"
      - "./data/mosquitto:/mosquitto/data"
      - "./log/mosquitto:/mosquitto/log"
    environment:
      - TZ=ETC/UTC
    restart: unless-stopped

  zwave-js-ui:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui
    devices:
      - ${ZWAVE_DEVICE_ID}:/dev/zwave
    env_file:
      - .env
    environment:
      ZWAVEJS_EXTERNAL_CONFIG: /usr/src/app/db
    ports:
      - 3002:3000
      - 8091:8091
    volumes:
      - ./data/zwave-js-ui/store:/usr/src/app/store
      - ./data/zwave-js-ui/db:/usr/src/app/db
    restart: unless-stopped

  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:0.13.2
    shm_size: "64mb" # update for your cameras based on calculation above
    devices:
      # - /dev/bus/usb:/dev/bus/usb  # Passes the USB Coral, needs to be modified for other versions
      # - /dev/apex_0:/dev/apex_0    # Passes a PCIe Coral, follow driver instructions here https://coral.ai/docs/m2/get-started/#2a-on-linux
      - /dev/video11:/dev/video11  # For Raspberry Pi 4B
      # - /dev/dri/renderD128:/dev/dri/renderD128 # For intel hwaccel, needs to be updated for your hardware
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config/frigate:/config
      - /mnt/Surveillance:/media/frigate
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    env_file:
      - .env
    restart: unless-stopped
