# yaml-language-server: $schema=http://localhost:9191/api/config/schema.json

mqtt:
  enabled: True
  host: mosquitto

ffmpeg:
  hwaccel_args: preset-vaapi
  output_args:
    record: preset-record-generic-audio-aac

detectors:
  ov:
    type: openvino
    device: CPU

model:
  width: 300
  height: 300
  input_tensor: nhwc
  input_pixel_format: bgr
  path: /openvino-model/ssdlite_mobilenet_v2.xml
  labelmap_path: /openvino-model/coco_91cl_bkgr.txt

motion:
  threshold: 50

cameras:
  front_doorbell:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/front_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/front_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

  back_doorbell:
    enabled: True
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/back_doorbell
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/back_doorbell_sub
          input_args: preset-rtsp-restream
          roles:
            - detect

go2rtc:
  streams:
    front_doorbell:
      - "ffmpeg:http://10.0.30.2/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USERNAME}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=aac"
      - rtsp://10.0.30.2/Preview_01_sub
    front_doorbell_sub:
      - "ffmpeg:http://10.0.30.2/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USERNAME}&password={FRIGATE_CAMERA_PASSWORD}"
    back_doorbell:
      - "ffmpeg:http://10.0.30.3/flv?port=1935&app=bcs&stream=channel0_main.bcs&user={FRIGATE_CAMERA_USERNAME}&password={FRIGATE_CAMERA_PASSWORD}#video=copy#audio=copy#audio=aac "
      - rtsp://10.0.30.2/Preview_01_sub
    back_doorbell_sub:
      - "ffmpeg:http://10.0.30.3/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user={FRIGATE_CAMERA_USERNAME}&password={FRIGATE_CAMERA_PASSWORD}"

record:
  enabled: True
  retain:
    days: 7
    mode: all
  events:
    retain:
      default: 30
      mode: motion

snapshots:
  enabled: True
